// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc6Lxklp9KQgUlIrwC_AV4CT_sOFLyo_E',
    appId: '1:806035976875:web:3623032d00ac2755927dee',
    messagingSenderId: '806035976875',
    projectId: 'employee-detail-99c0c',
    authDomain: 'employee-detail-99c0c.firebaseapp.com',
    storageBucket: 'employee-detail-99c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0PyWaOwtrvNxritURlO8Zza1dQGSdqI',
    appId: '1:806035976875:android:f359da9bae2b9f4f927dee',
    messagingSenderId: '806035976875',
    projectId: 'employee-detail-99c0c',
    storageBucket: 'employee-detail-99c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPtM4aodPe0Fq5CBX7VckpTQoTAk-weQ',
    appId: '1:806035976875:ios:9c8df2c9ab305e11927dee',
    messagingSenderId: '806035976875',
    projectId: 'employee-detail-99c0c',
    storageBucket: 'employee-detail-99c0c.appspot.com',
    iosBundleId: 'com.example.employeeList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPtM4aodPe0Fq5CBX7VckpTQoTAk-weQ',
    appId: '1:806035976875:ios:e85a73a2a7c748ab927dee',
    messagingSenderId: '806035976875',
    projectId: 'employee-detail-99c0c',
    storageBucket: 'employee-detail-99c0c.appspot.com',
    iosBundleId: 'com.example.employeeList.RunnerTests',
  );
}
